foodtasker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from foodtaskerapp import views, api

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),

    # Restaurant
    url(r'^restaurant/sign-in/$', auth_views.login,
        {'template_name': 'restaurant/sign-in.html'},
        name='restaurant-sign-in'),
    url(r'^restaurant/sign-out/$', auth_views.logout,
        {'next_page': '/'},
        name='restaurant-sign-out'),
    url(r'^restaurant/sign-up/$', views.restaurant_sign_up,
            name='restaurant-sign-up'),
    url(r'^restaurant/$', views.restaurant_home, name='restaurant-home'),
    url(r'^restaurant/account/$', views.restaurant_account,
            name='restaurant-account'),
    url(r'^restaurant/meal/$', views.restaurant_meal,
        name='restaurant-meal'),
    url(r'^restaurant/meal/add/$', views.restaurant_add_meal,
        name='restaurant-add-meal'),
    url(r'^restaurant/meal/edit/(?P<meal_id>\d+)/$', views.restaurant_edit_meal,
        name='restaurant-edit-meal'),
    url(r'^restaurant/order/$', views.restaurant_order,
        name='restaurant-order'),
    url(r'^restaurant/report/$', views.restaurant_report,
        name='restaurant-report'),

    # API Sign-In / Sign-Up / Sign-Out
    # /convert-token (for sign in / sign up)
    # /revoke-token (fir sign out)
    url(r'^api/social/', include('rest_framework_social_oauth2.urls')),

    # APIs for Customers
    url(r'^api/customer/restaurants/$', api.customer_get_restaurants),
    url(r'^api/customer/meals/(?P<restaurant_id>\d+)/$', api.customer_get_meals),
    url(r'^api/customer/order/add/$', api.customer_add_order),
    url(r'^api/customer/order/latest/$', api.customer_get_latest_order),
    url(r'^api/restaurant/order/notification/(?P<last_request_time>.+)/$', api.restaurant_order_notification),
    url(r'^api/customer/driver/location/$', api.customer_driver_location),

    # Driver APIs
    url(r'^api/driver/orders/ready/$', api.driver_get_ready_orders),
    url(r'^api/driver/order/pick/$', api.driver_pick_order),
    url(r'^api/driver/orders/latest/$', api.driver_get_latest_order),
    url(r'^api/driver/orders/complete/$', api.driver_complete_order),
    url(r'^api/driver/revenue/$', api.driver_get_revenue),
    url(r'^api/driver/location/update/$', api.driver_update_location),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodtaskerapp/models.py
"""
Author: Pierre-Henry Soria <hi@ph7.me>
Copyright: Pierre-Henry Soria, All Rights Reserved.
"""

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Restaurant(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='restaurant')
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=80)
    address = models.CharField(max_length=200)
    logo = models.ImageField(upload_to='restaurant_logo/', blank=False)

    def __str__(self):
        return self.name

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='customer')
    avatar = models.CharField(max_length=500)
    phone = models.CharField(max_length=500, blank=True)
    address = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.user.get_full_name()

class Driver(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='driver')
    avatar = models.CharField(max_length=500)
    phone = models.CharField(max_length=500, blank=True)
    address = models.CharField(max_length=500, blank=True)
    location = models.CharField(max_length=250, blank=True)

    def __str__(self):
        return self.user.get_full_name()

class Meal(models.Model):
    restaurant = models.ForeignKey(Restaurant)
    name = models.CharField(max_length=500)
    short_description = models.CharField(max_length=500)
    image = models.ImageField(upload_to='meal_images/', blank=False)
    price = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Order(models.Model):
    COOKING = 1
    READY = 2
    ONTHEWAY = 3
    DELIVERED = 4

    STATUS_CHOICES = (
        (COOKING, 'Cooking'),
        (READY, 'Ready'),
        (ONTHEWAY, 'On the way'),
        (DELIVERED, 'Delivered'),
    )

    customer = models.ForeignKey(Customer)
    restaurant = models.ForeignKey(Restaurant)
    driver = models.ForeignKey(Driver, blank = True, null = True)
    address = models.CharField(max_length=120)
    total = models.IntegerField()
    status = models.IntegerField(choices = STATUS_CHOICES)
    created_at = models.DateTimeField(default = timezone.now)
    picked_at = models.DateTimeField(blank = True, null = True)

    def __str__(self):
        return str(self.id)

class OrderDetails(models.Model):
    order = models.ForeignKey(Order, related_name='order_details')
    meal = models.ForeignKey(Meal)
    quantity = models.IntegerField()
    sub_total = models.IntegerField()

    def __str__(self):
        return str(self.id)

foodtaskerapp/forms.py
"""
Author: Pierre-Henry Soria <hi@ph7.me>
Copyright: Pierre-Henry Soria, All Rights Reserved.
"""

from django import forms
from django.contrib.auth.models import User
from foodtaskerapp.models import Restaurant, Meal

class UserForm(forms.ModelForm):
    email = forms.EmailField(max_length=120, required=True)
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password', 'first_name', 'last_name', 'email')

class UserEditForm(forms.ModelForm):
    email = forms.EmailField(max_length=120, required=True)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = ('name', 'phone', 'address', 'logo')

class MealForm(forms.ModelForm):
    class Meta:
        model = Meal
        exclude = ('restaurant',)

foodtaskerapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.db.models import Sum, Count, Case, When

from foodtaskerapp.models import Meal, Order, Driver
from foodtaskerapp.forms import UserForm, RestaurantForm, UserEditForm, MealForm
from foodtaskerapp.util import get_current_weekdays

def home(request):
    return redirect(restaurant_home)

@login_required(login_url='/restaurant/sign-in/')
def restaurant_home(request):
    return redirect(restaurant_order)

@login_required(login_url='/restaurant/sign-in/')
def restaurant_account(request):
    user_form = UserEditForm(instance = request.user)
    restaurant_form = RestaurantForm(instance = request.user.restaurant)

    if request.user.restaurant.logo:
        restaurant_form.fields['logo'].required = False

    if request.method == 'POST':
        # Update the data
        user_form = UserEditForm(request.POST, instance = request.user)
        restaurant_form = RestaurantForm(request.POST, request.FILES, instance = request.user.restaurant)

        if user_form.is_valid() and restaurant_form.is_valid():
            user_form.save()
            restaurant_form.save()

    return render(request, 'restaurant/account.html', {
        'user_form': user_form,
        'restaurant_form': restaurant_form
    })

@login_required(login_url='/restaurant/sign-in/')
def restaurant_meal(request):
    meals = Meal.objects.filter(restaurant = request.user.restaurant).order_by('-id')

    return render(request, 'restaurant/meal.html', {
        'meals': meals
    })

@login_required(login_url='/restaurant/sign-in/')
def restaurant_add_meal(request):
    meal_form = MealForm()

    if request.method == 'POST':
        meal_form = MealForm(request.POST, request.FILES)

        if meal_form.is_valid():
            meal = meal_form.save(commit=False)
            meal.restaurant = request.user.restaurant
            meal.save()
            return redirect(restaurant_meal)

    return render(request, 'restaurant/add-meal.html', {
        'meal_form': meal_form
    })

@login_required(login_url='/restaurant/sign-in/')
def restaurant_edit_meal(request, meal_id):
    meal_form = MealForm(instance = Meal.objects.get(id = meal_id))

    if request.method == 'POST':
        meal_form = MealForm(request.POST, request.FILES, instance = Meal.objects.get(id = meal_id))

        if meal_form.is_valid():
            meal_form.save()
            return redirect(restaurant_meal)

    return render(request, 'restaurant/edit-meal.html', {
        'meal_form': meal_form
    })

@login_required(login_url='/restaurant/sign-in/')
def restaurant_order(request):
    if request.method == 'POST':
        order = Order.objects.get(id = request.POST.get('id'), restaurant = request.user.restaurant)

        if order.status == Order.COOKING:
            order.status = Order.READY
            order.save()

    orders = Order.objects.filter(restaurant = request.user.restaurant).order_by('-id')

    return render(request, 'restaurant/order.html', {'orders': orders})

@login_required(login_url='/restaurant/sign-in/')
def restaurant_report(request):
    """ Calculate revenue and number of order by current week"""

    revenue = []
    orders = []

    current_weekdays = get_current_weekdays()

    for day in current_weekdays:
        delivered_orders = Order.objects.filter(
            restaurant = request.user.restaurant,
            status = Order.DELIVERED,
            created_at__year = day.year,
            created_at__month = day.month,
            created_at__day = day.day
        )
        revenue.append(sum(order.total for order in delivered_orders))
        orders.append(delivered_orders.count())

    top_meals = Meal.objects.filter(restaurant = request.user.restaurant)\
        .annotate(total_order = Sum('orderdetails__quantity'))\
        .order_by('total_order')[:3]

    meals = {
        "labels": [meal.name for meal in top_meals],
        "data": [meal.total_order or 0 for meal in top_meals]
    }

    top_drivers = Driver.objects.annotate(
        total_order = Count(
            Case (
                When(order__restaurant = request.user.restaurant, then = 1)
            )
        )
    ).order_by('-total_order')[:3]

    drivers = {
        "labels": [driver.user.get_full_name() for driver in top_drivers],
        "data": [driver.total_order for driver in top_drivers]
    }

    return render(request, 'restaurant/report.html', {
        "revenue": revenue,
        "orders": orders,
        "meals": meals,
        "drivers": drivers
    })

def restaurant_sign_up(request):
    user_form = UserForm()
    restaurant_form = RestaurantForm()

    if request.method == "POST":
        user_form = UserForm(request.POST)
        restaurant_form = RestaurantForm(request.POST, request.FILES)

        if user_form.is_valid() and restaurant_form.is_valid():
            new_user = User.objects.create_user(**user_form.cleaned_data)
            new_restaurant = restaurant_form.save(commit=False) # Just create the object in memory. Not committing to a data
            new_restaurant.user = new_user
            new_restaurant.save() # Save into the DB

            login(request, authenticate(
                username = user_form.cleaned_data['username'],
                password = user_form.cleaned_data['password']
            ))

            # Redirect the user to the homepage
            return redirect(restaurant_home)
        else:
            raise forms.ValidationError('You are already registered.')

    return render(request, 'restaurant/sign-up.html', {
        'user_form': user_form,
        'restaurant_form': restaurant_form
    })

foodtaskerapp/templates/restaurant/account.html
{% extends 'restaurant/base.html' %}
{% load bootstrap3 %}

{% block page %}
    <div class="col-lg-offset-2 col-lg-8">
        <div class="panel">
            <div class="panel-heading bg-blue">
                <h4 class="panel-titlle-center text-white">
                    Account
                </h4>
            </div>
            <div class="panel-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form user_form %}
                    {% bootstrap_form restaurant_form %}
                    <button type="submit" class="btn btn-pink">Update</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

foodtaskerapp/templates/restaurant/add-meal.html
{% extends 'restaurant/base.html' %}
{% load bootstrap3 %}

{% block page %}
    <div class="col-lg-offset-2 col-lg-8">
        <div class="panel">
            <div class="panel-heading bg-blue">
                <h4 class="panel-titlle-center text-white">
                    Add Meal
                </h4>
            </div>
            <div class="panel-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form meal_form %}
                    <button type="submit" class="btn btn-pink">Create</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

foodtaskerapp/templates/restaurant/base.html
{% extends 'base.html' %}

{% block title %}Restaurant Delivery as a Service{% endblock %}

{% block script %}
    <script>
        $(function() {
            var now = new Date(), pageTitle = document.title;
            setInterval(function() {
                $.ajax({
                    url: '/api/restaurant/order/notification/' + now.toISOString() + '/',
                    method: 'GET',
                    success: function(data) {
                        if (data['notification'] === 0) {
                            $('.badge').text(''); // Clear the text
                        } else {
                            document.title = '(' + data['notification'] +') ' + pageTitle;
                            $('.badge').text(data['notification']);
                        }
                    }
                })
            }, 2000)
        });
    </script>
{% endblock %}

{% block sidebar %}

    {# for the active sidebar buttons #}
    {% url 'restaurant-order' as order_url %}
    {% url 'restaurant-meal' as meal_url %}
    {% url 'restaurant-report' as report_url %}
    {% url 'restaurant-account' as account_url %}

    <div class="text-center">
        <img
            class="img-circle"
            src="{{ MEDIA_URL }}{{ request.user.restaurant.logo }}"
            alt="{{ request.user }}"
            width="70"
            height="70"
        />
        <h4>Hi {{ request.user.get_full_name }}</h4>
        <h5>{{ request.user.restaurant.name }}</h5>
    </div>

    <nav class="list-group">
        <span class="text-uppercase">
            Dashboard
        </span>
        <a
            href="{% url 'restaurant-order' %}"
            class="list-group-item{% if request.path == order_url %} active{% endif %}"
            >Orders
            <span class="badge"></span>
        </a>

        <a
            href="{% url 'restaurant-meal' %}"
            class="list-group-item{% if request.path == meal_url %} active{% endif %}"
            >Meals
        </a>
        <a
            href="{% url 'restaurant-report' %}"
            class="list-group-item{% if request.path == report_url %} active{% endif %}"
            >Reports
        </a>

        <span class="text-uppercase">
            Profile
        </span>
        <a
            href="{% url 'restaurant-account' %}"
            class="list-group-item{% if request.path == account_url %} active{% endif %}"
            >Account
        </a>
    </nav>

    <nav class="text-center">
        <a
            href="{% url 'restaurant-sign-out' %}?next={{ request.path }}"
            class="btn btn-pink">Logout
        </a>
    </nav>
{% endblock %}

foodtaskerapp/templates/restaurant/edit-meal.html
{% extends 'restaurant/base.html' %}
{% load bootstrap3 %}

{% block page %}
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel">
            <div class="panel-heading bg-blue">
                <h4 class="panel-titlle-center text-white">
                    Edit Meal
                </h4>
            </div>
            <div class="panel-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form meal_form %}
                    <button type="submit" class="btn btn-pink">Update</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

foodtaskerapp/templates/restaurant/meal.html
{% extends 'restaurant/base.html' %}

{% block page %}
    <div class="panel">
        <div class="panel-heading bg-blue">
            <h4 class="panel-title text-center text-white">
                Meals
            </h4>
        </div>

        <div class="panel-body">
            <div class="text-right">
                <p><a href="{% url 'restaurant-add-meal' %}" class="btn btn-pink">Add Meal</a></p>
            </div>

            <table class="table table-bordered table-hover table-striped">
                <thead>
                    <tr class="bg-gray text-white">
                        <th>ID#</th>
                        <th>Name</th>
                        <th>Short Description</th>
                        <th>Price</th>
                        <th class="text-center">Image</th>
                    </tr>
                </thead>

                <tbody>
                    {% for meal in meals %}
                        <tr>
                            <td scrope="row">{{ meal.id }}</td>
                            <td><a href="{% url 'restaurant-edit-meal' meal.id %}" title="Edit It">{{ meal.name }}</a></td>
                            <td>{{ meal.short_description }}</td>
                            <td>{{ meal.price }}</td>
                            <td class="text-center">
                                <img class="img-rounded" src="{{ MEDIA_URL}}{{ meal.image }}" width="50" height="50" alt="Meal Image">
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

foodtaskerapp/templates/restaurant/order.html
{% extends 'restaurant/base.html' %}

{% block page %}
    <div class="panel">
        <div class="panel-heading bg-blue">
            <h4 class="panel-title text-center text-white">
                Orders
            </h4>
        </div>

        <div class="panel-body">
            <table class="table table-bordered table-hover table-striped">
                <thead>
                    <tr class="bg-gray text-white">
                        <th>ID#</th>
                        <th>Order Details</th>
                        <th>Customer</th>
                        <th>Driver</th>
                        <th>Total</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>

                <tbody>
                    {% for order in orders %}
                        <tr>
                            <td>{{ order.id }}</td>
                            <td>
                                 {% for order_details in order.order_details.all %}
                                    {{ order_details.meal.name }}
                                    {{ order_details.meal.price }}
                                    x {{ order_details.quantity }}
                                    = ${{ order_details.sub_total }}
                                {% endfor %}
                            </td>
                            <td>{{ order.customer }}</td>
                            <td>{{ order.driver }}</td>
                            <td>{{ order.total }}</td>
                            <td>{{ order.get_status_display }}</td>
                            <td>
                                {% if order.status == 1 %}
                                    <form method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="id" value="{{ order.id }}">
                                        <button class="btn btn-success">Ready</button>
                                    </form>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

foodtaskerapp/templates/restaurant/report.html
{% extends 'restaurant/base.html' %}

{% block script %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.bundle.js"></script>
    <script>
        /** Revenue Chart **/
        var revenueChart = document.getElementById('revenue-chart').getContext('2d');
        var data = {
            labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            datasets: [
                {
                    label: "Revenue per Week",
                    backgroundColor: "rgba(54,162,235,0.9)",
                    hoverBackgroundColor: "rgba(54,162,235,1)",
                    data: {{ revenue }}
                }
            ]
        };
        new Chart(revenueChart, {
            type: 'bar',
            data: data
        });

        /** Order Chart **/
        var orderChart = document.getElementById('order-chart').getContext('2d');
        var data = {
            labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            datasets: [
                {
                    label: "Order per Week",
                    backgroundColor: "rgba(255,99,132,0.9)",
                    hoverBackgroundColor: "rgba(255,99,132,1)",
                    data: {{ orders }}
                }
            ]
        };
        new Chart(orderChart, {
            type: 'bar',
            data: data
        });

        /** Top Meals Chart **/
        var mealChart = document.getElementById('meal-chart').getContext('2d');
        var data = {
            labels: {{ meals.labels|safe }},
            datasets: [
                {
                    backgroundColor: [
                        '#36A2EB',
                        '#FFCE56',
                        '#FF6384'
                    ],
                    data: {{ meals.data }}
                }
            ]
        };
        new Chart(mealChart, {
            type: 'pie',
            data: data
        });

        /** Top Drivers Chart **/
        var driverChart = document.getElementById('driver-chart').getContext('2d');
        var data = {
            labels: {{ drivers.labels|safe }},
            datasets: [
                {
                    backgroundColor: [
                        '#36A2EB',
                        '#FFCE56',
                        '#FF6384'
                    ],
                    data: {{ drivers.data }}
                }
            ]
        };
        new Chart(driverChart, {
            type: 'pie',
            data: data
        });
    </script>
{% endblock %}

{% block page %}
    <div class="row">
        <div class="col-lg-8">
            <div class="panel">
                <div class="panel-heading bg-blue">
                    <h4 class="panel-title text-center text-white">
                        Revenue per Week
                    </h4>
                </div>
                <div class="panel-body">
                    <canvas id="revenue-chart" height="110"></canvas>
                </div>
            </div>

            <div class="panel">
                <div class="panel-heading bg-blue">
                    <h4 class="panel-title text-center text-white">
                        Order per Week
                    </h4>
                </div>
                <div class="panel-body">
                    <canvas id="order-chart" height="110"></canvas>
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="panel">
                <div class="panel-heading bg-blue">
                    <h4 class="panel-title text-center text-white">
                        Top Meals
                    </h4>
                </div>
                <div class="panel-body">
                    <canvas id="meal-chart" height="200"></canvas>
                </div>
            </div>

            <div class="panel">
                <div class="panel-heading bg-blue">
                    <h4 class="panel-title text-center text-white">
                        Top Drivers
                    </h4>
                </div>
                <div class="panel-body">
                    <canvas id="driver-chart" height="200"></canvas>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

foodtaskerapp/templates/restaurant/sign-in.html
{% extends 'base-signup.html' %}
{% load bootstrap3 %}

{% block title %}Sign In{% endblock %}
{% block heading %}Restaurant - Sign In{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-pink pull-right">Sign In</button>
    </form>
    <p class="bold"><a href="{% url 'restaurant-sign-up' %}">Become a Restaurant</a></p>
{% endblock %}

foodtaskerapp/templates/restaurant/sign-up.html
{% extends 'base-signup.html' %}
{% load bootstrap3 %}

{% block title %}Sign Up{% endblock %}
{% block heading %}Restaurant - Sign Up{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form user_form %}
        {% bootstrap_form restaurant_form %}
        <button type="submit" class="btn btn-pink pull-right">Sign Up</button>
    </form>
    <p><a href="{% url 'restaurant-sign-in' %}">Already Registered?</a></p>
{% endblock %}